geoffrey:
  geoffrey_api_key:
    default: "geoffreybot:test@geoffrey"
    client: false
  geoffrey_public_key:
    default: "geoffrey"
    client: true
  geoffrey_endpoint:
   default: "http://geoffrey.dev/"
   client: true
   hidden: true